tasks:
  - name: keploy-server
    openMode: split-right
    before: |
      curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
      sudo mv /tmp/keploy /usr/local/bin && keploy
  - name: echo-sql-sample-application
    openMode: split-right
    before: |
      cd echo-sql && go mod download
    init: |
      docker-compose up -d
    command: |
      export KEPLOY_MODE=record && go run handler.go main.go